### PR TITLE
Recompile dependants and notify browsersync of updated .css

### PR DESCRIPTION
**Pull request by swist**
I was rewriting some history and turned out i removed the previous discussion.

@lookfirst how does it look to you? Would this work for your use case?

### CODE REVIEW

**Comment by lookfirst** [comment]
Nice! released... gulp-debug looks nice too!

**Comment by lookfirst** [comment]
@swist the PR was missing gulp-filter in package.json, so I added that.

Also, it seems like it is recompiling ALL my .less files instead of the ones in the dependency tree... not the end of the world, but it would be nice if it was a bit smarter about things.

**Comment by swist** [comment]
if you can come up with a reduced test case, I am willing to see if we could filter out unnecessary recompiles somehow. LESS stylesheets can get quite bulky quite quickly

**Comment by lookfirst** [comment]
@swist Ugh... time is at a premium right now for me... it would be nice to have some tests around this in gulp-helpers...hmmm...

**Comment by lookfirst** [comment]
I basically have a folder of .less files. I use `@import (reference) 'foo'` a lot.

**Pull request merged**
